/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ee93ed",
        "inverse-surface": "#040a2f",
        "surface-container-low": "#f0efff",
        "on-surface": "#262c51",
        primary: "#0055c7",
        "on-tertiary-fixed": "#4b0051",
        "inverse-on-surface": "#959ac6",
        "outline-variant": "#a5aad7",
        "surface-variant": "#d7daff",
        "on-primary-container": "#002054",
        "on-surface-variant": "#535981",
        "on-primary": "#f0f2ff",
        "on-error-container": "#570008",
        "surface-container-high": "#dee0ff",
        surface: "#f7f5ff",
        "primary-container": "#749eff",
        "inverse-primary": "#578cff",
        error: "#b31b25",
        "on-tertiary": "#ffeef9",
        "on-background": "#262c51",
        outline: "#6e749e",
        "on-secondary-fixed": "#11268f",
        secondary: "#4152b7",
        "on-secondary-container": "#2a3ca2",
        "on-tertiary-fixed-variant": "#712276",
        "surface-tint": "#0055c7",
        "tertiary-container": "#fda0fc",
        "primary-fixed": "#749eff",
        background: "#f7f5ff",
        "primary-fixed-dim": "#5c8fff",
        "secondary-fixed": "#c9cfff",
        "surface-container-highest": "#d7daff",
        "on-tertiary-container": "#67176c",
        "surface-bright": "#f7f5ff",
        tertiary: "#8b3b8e",
        "on-error": "#ffefee",
        "tertiary-fixed": "#fda0fc",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fb5151",
        "on-primary-fixed": "#000000",
        "secondary-container": "#c9cfff",
        "surface-container": "#e5e6ff",
        "secondary-fixed-dim": "#b7c0ff",
        "on-secondary-fixed-variant": "#3546ac",
        "on-secondary": "#f3f1ff",
        "on-primary-fixed-variant": "#002867",
        "surface-dim": "#cdd2ff",
        "tertiary-dim": "#7d2e81",
        "primary-dim": "#004aaf",
        "secondary-dim": "#3445ab",
        "error-dim": "#9f0519",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "container-max": "1200px",
        "margin-desktop": "64px",
        unit: "8px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        caption: ["Inter"],
        headline: ["Plus Jakarta Sans"],
        display: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
